#!/bin/bash

setp(){
    m $1
    cd $1
    #touch main.py database.py schemas.py crud.py 
}

setpwurl() {
    echo "With url"
}

help_text() {
    echo "Usage: fastapi [project name] [database_url]"
    echo "--help      Display this information"
    echo "-h          Display this information"
    echo "-v          Display current version"
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    help_text
elif [ -n "$2" ] ; then
    setpwurl
else
    setp $1
fi
